modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="sheepconsistencyforge"
version="${file.jarVersion}"
displayName="Sheep Consistency Forge"
authors="Crupette & JSBOfficial"
logoFile="icon.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sheep-consistency-unofficial-forge-port"
description="Makes the sheared variants of sheep match the colors they were dyed with. Based on bedrock version of sheep."

[[dependencies.sheepconsistencyforge]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.14,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.sheepconsistencyforge]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="CLIENT"
[modproperties.sheepconsistencyforge]
    catalogueItemIcon="icon.png" #Support for Catalogue mod
